# Server Configuration
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://ayushdb-rajputayushsingh070420041-da4c.i.aivencloud.com:20504/defaultdb?ssl=require&user=&password=
#spring.datasource.username=
#spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver

# Optional, but recommended for connection validation
spring.datasource.hikari.connection-test-query=SELECT 1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# WebSocket
spring.web.socket.enabled=true

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=official.codezy@gmail.com

spring.mail.password=${_EMAIL_PASSCODE}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logging
logging.level.org.springframework=INFO


