package com.codeColab.codab.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@Entity
@Data
@AllArgsConstructor
public class CollaborationSession {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // Primary key

    public void setId(Long id) {
        this.id = id;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public void setContent(String content) {
        this.content = content;
    }

    private String sessionId;    // Unique session ID
    private String projectName;  // Name of the project
    private String content;      // Initial content

    // No-argument constructor (generated by Lombok or explicitly declared)
    public CollaborationSession() {
    }

    // Parameterized constructor for creating objects manually
    public CollaborationSession(String sessionId, String projectName, String content) {
        this.sessionId = sessionId;
        this.projectName = projectName;
        this.content = content;
    }
}
